/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerBaseCtrl;
import Controller.CtrlCliente;
import View.Mensagens.Mensagem;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;

/**
 *
 * @author Abner Amorim
 */
public class Cliente extends javax.swing.JDialog {

    /**
     * Creates new form CadastroCliente
     */
    private JsonParser objParser;
    private JsonObject objJsonObject;
    private boolean isAlterar;
    private Gson objGson;
    private ControllerBaseCtrl objCtrlCli;
    private int codBackup = -1;

    public Cliente(java.awt.Frame parent, boolean modal, int pCodigoInicial) {
        super(parent, modal);
        initComponents();
        Util.Util.temaVisualizacao(this);
        objParser = new JsonParser();
        objGson = new Gson();
        objCtrlCli = new CtrlCliente();
        if (pCodigoInicial > 0) {
            setJsonTelaCliente(objCtrlCli.Recuperar(pCodigoInicial));
        } else {
            setJsonTelaCliente(objCtrlCli.RecuperaPrimeiroRegistro());
        }
        isAlterar = false;
        controlaAcesso(true);
    }

    public String toJsonCliente() throws Exception {
        objJsonObject = new JsonObject();

        objJsonObject.add("nome_cli", new JsonPrimitive(txtNome.getText()));
        if (txtCartao.getText().length() == 22) {
            objJsonObject.add("cartao_cli", new JsonPrimitive(txtCartao.getText()));
        } else {
            Mensagem.error("Cartão Incoreto", this);
            return null;
        }
        if (isAlterar) {
            objJsonObject.add("objCod_objBase", new JsonPrimitive(Integer.parseInt(txtCodigo.getText())));
        }

        //System.out.println(new Gson().toJson(objJsonObject));
        return new Gson().toJson(objJsonObject);
    }

    public void setJsonTelaCliente(String json) {
        if (json == null || json.isEmpty()) {
            return;
        }

        objJsonObject = objParser.parse(json).getAsJsonObject();
        txtNome.setText(objJsonObject.get("nome_cli").getAsString());
        txtCodigo.setText(objJsonObject.get("objCod_objBase").getAsString());
        txtCartao.setText(objJsonObject.get("cartao_cli").getAsString());
    }

    private void controlaAcesso(boolean status) {
        btnIncluir.setEnabled(status);
        btnSalvar.setEnabled(!status);
        btnExcluir.setEnabled(status);
        btnAlterar.setEnabled(status);
        btnCancelar.setEnabled(!status);
        txtNome.setEditable(!status);
        txtCartao.setEditable(!status);
        btnPrimeiro.setEnabled(status);
        btnAnterior.setEnabled(status);
        btnProximo.setEnabled(status);
        btnUltimo.setEnabled(status);
        txtCodigo.setEnabled(status);
    }

    private void limpaTelaCompleta() {
        txtNome.setText("");
        txtCartao.setText("");
        txtCodigo.setText("");
    }

    private void atualizaTela() {
        ControllerBaseCtrl ctrlCli = new CtrlCliente();
        int codigoCli = Integer.parseInt(txtCodigo.getText());
        String json;
        json = ctrlCli.Recuperar(codigoCli);
        limpaTelaCompleta();
        if (!json.isEmpty()) {
            setJsonTelaCliente(json);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabelCartao = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCartao = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(289, 80));

        jLabel1.setText("Codigo:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/logo_mini.png"))); // NOI18N

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/last_mini.png"))); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/next_mini.png"))); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/previous_mini.png"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/first_mini.png"))); // NOI18N
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnterior, btnPrimeiro, btnProximo, btnUltimo});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProximo))
                            .addComponent(btnAnterior)
                            .addComponent(btnPrimeiro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAnterior, btnPesquisar, btnPrimeiro, btnProximo, btnUltimo, jLabel1, txtCodigo});

        jLabelNome.setText("Nome:");

        jLabelCartao.setText("Cartão:");

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/create.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/trash.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/close.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/back.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(176, 176, 176))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnIncluir, btnSalvar, jButton2});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnIncluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnIncluir, btnSalvar, jButton2});

        try {
            txtCartao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("# ### #### ###### ## #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCartao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCartaoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabelNome)
                    .addGap(4, 4, 4)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabelCartao)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCartao, txtNome});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelCartao))
                    .addComponent(txtCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCartao, txtNome});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        txtNome.requestFocus();
        controlaAcesso(false);
        isAlterar = false;
        if(!txtCodigo.getText().isEmpty())
            codBackup = Integer.parseInt(txtCodigo.getText());
        limpaTelaCompleta();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            //System.out.println("Cliente: " + toJsonCliente());
            CtrlCliente CTRLCli = new CtrlCliente();
            if (toJsonCliente() == null) {
                return;
            }
            int codigoCli = CTRLCli.Salvar(toJsonCliente());
            txtCodigo.setText(String.valueOf(codigoCli));
            Mensagem.information("Cliente cadastrado com sucesso", this);
            //atualizaTela();
            controlaAcesso(true);
        } catch (Exception ex) {
            if (ex.getMessage().contains("Duplicate entry")) {
                Mensagem.error("Já existe um cliente com a carteira informada !!!", this);
                txtCartao.selectAll();
            } else {
                Mensagem.error("Não foi possivel cadastrar o cliente", this);
            }
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        controlaAcesso(false);
        isAlterar = true;
        if(!txtCodigo.getText().isEmpty())
            codBackup = Integer.parseInt(txtCodigo.getText());
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(!Mensagem.confirm("Deseja excluir este cliente?", this)){
            return;
        }
        int codigo = txtCodigo.getText().isEmpty() ? 0 : Integer.parseInt(txtCodigo.getText());
        if (codigo > 0) {
            objCtrlCli.Deletar(codigo);
            Mensagem.information("Cliente excluido com sucesso", this);
            limpaTelaCompleta();
            setJsonTelaCliente(new CtrlCliente().RecuperaRegistroAnterior(codigo));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(!Mensagem.confirm("Deseja descartar as alterações?", this)){
            return;
        }
        controlaAcesso(true);
        CtrlCliente CTRLCli = new CtrlCliente();
        if (!isAlterar) {
            setJsonTelaCliente(CTRLCli.Recuperar(codBackup));
        } else {
            setJsonTelaCliente(CTRLCli.Recuperar(Integer.parseInt(txtCodigo.getText())));
        }
        codBackup = -1;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        txtCodigo.selectAll();
    }//GEN-LAST:event_txtCodigoFocusGained

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            ControllerBaseCtrl ctrlCli = new CtrlCliente();
            int codigoCli = Integer.parseInt(txtCodigo.getText());
            String json;
            //limpaTelaCompleta();
            if (codigoCli > 0) { //Pesquisa direta
                json = ctrlCli.Recuperar(codigoCli);

                if (json.isEmpty()) {
                    if (Mensagem.confirm("Cliente não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                        Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "CLIENTE", new String());
                        pesq.setVisible(true);
                        //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                        setJsonTelaCliente(new CtrlCliente().RecuperarCliCompCartao(pesq.getResultPesq()));
                    }
                    return;
                } else {
                    setJsonTelaCliente(json);
                    controlaAcesso(true);
                }
            } else { //Abre a tela de pesquisa
                setJsonTelaCliente(new CtrlCliente().RecuperaUltimoRegistro());
            }
        } catch (NumberFormatException ex) {
            txtCodigo.requestFocus();

        } catch (Exception ex) {
            Mensagem.warning(ex.getMessage(), this);
        } finally {
            txtCodigo.selectAll();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == 10) {
            btnPesquisarActionPerformed(new java.awt.event.ActionEvent(this, WIDTH, "Salvar"));
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlCliente objCtrlCli = new CtrlCliente();
            String Cliente = objCtrlCli.RecuperaUltimoRegistro();
            if (Cliente == null) {
                Mensagem.information("Erro ao recuperar o último registro !!!", this);
                return;
            }

            setJsonTelaCliente(Cliente);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlCliente objCtrlCli = new CtrlCliente();
            String Cliente = objCtrlCli.RecuperaProximoRegistro(Integer.parseInt(txtCodigo.getText()));
            if (Cliente == null) {
                Mensagem.information("Este é o último registro !!!", this);
                return;
            }

            setJsonTelaCliente(Cliente);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        
        if (!txtCodigo.getText().isEmpty()) {
            CtrlCliente objCtrlCli = new CtrlCliente();
            String Cliente = objCtrlCli.RecuperaRegistroAnterior(Integer.parseInt(txtCodigo.getText()));
            if (Cliente == null) {
                Mensagem.information("Este é o primeiro registro !!!", this);
                return;
            }

            setJsonTelaCliente(Cliente);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlCliente objCtrlCli = new CtrlCliente();
            String Cliente = objCtrlCli.RecuperaPrimeiroRegistro();
            if (Cliente == null) {
                Mensagem.information("Erro ao recuperar o primeiro registro !!!", this);
                return;
            }

            setJsonTelaCliente(Cliente);
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void txtCartaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCartaoKeyPressed
        if(!txtCartao.isEditable()){
            return;
        }
        
        if((evt.getKeyCode() >= 33 && evt.getKeyCode() <= 40) || evt.getKeyCode() == 127 || evt.getKeyCode() == 8 || evt.getKeyCode() == 10)
                return;
        
        /*if (evt.getKeyCode() == 10) {
        btnSalvarActionPerformed(new java.awt.event.ActionEvent(this, WIDTH, "Salvar"));
        }*/
        
        if (!Character.isDigit(evt.getKeyChar())) {
            String texto = txtCartao.getText();
            int tamanho = texto.length();
            txtCartao.setText(texto.substring(0, tamanho));
            Mensagem.warning("Informe apenas números!!!", this);//System.out.println("Digito");
            return;
        }
    }//GEN-LAST:event_txtCartaoKeyPressed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            Cliente dialog = new Cliente(new javax.swing.JFrame(), true, -1);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCartao;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txtCartao;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
