/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerBaseCtrl;
import Controller.CtrlFabricante;
import Controller.CtrlSolicitante;
import View.Mensagens.Mensagem;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;

/**
 *
 * @author Abner Amorim
 */
public class Fabricante extends javax.swing.JDialog {

    /**
     * Creates new form CadastroCliente
     */
    private JsonParser objParser;
    private JsonObject objJsonObject;
    private boolean isAlterar;
    private Gson objGson;
    private ControllerBaseCtrl objCtrlFab;
    private int codBackup = -1;

    public Fabricante(java.awt.Frame parent, boolean modal, int pCodigoInicial) {
        super(parent, modal);
        initComponents();
        Util.Util.temaVisualizacao(this);
        objParser = new JsonParser();
        objGson = new Gson();
        objCtrlFab = new CtrlFabricante();
        if (pCodigoInicial > 0) {
            setJsonTelaFabricante(objCtrlFab.Recuperar(pCodigoInicial));
        } else {
            setJsonTelaFabricante(objCtrlFab.RecuperaUltimoRegistro());
        }
        isAlterar = false;
        controlaAcesso(true);
    }

    public String toJsonFabricante() throws Exception {
        objJsonObject = new JsonObject();

        objJsonObject.add("nome_fab", new JsonPrimitive(txtNomeFab.getText()));
        objJsonObject.add("cnpj_fab", new JsonPrimitive(txtCNPJ.getText()));

        if (isAlterar) {
            objJsonObject.add("objCod_objBase", new JsonPrimitive(Integer.parseInt(txtCodigo.getText())));
        }

        //System.out.println(new Gson().toJson(objJsonObject));
        return new Gson().toJson(objJsonObject);
    }

    public void setJsonTelaFabricante(String json) {
        if (json == null || json.isEmpty()) {
            return;
        }

        objJsonObject = objParser.parse(json).getAsJsonObject();
        txtNomeFab.setText(objJsonObject.get("nome_fab").getAsString());
        txtCodigo.setText(objJsonObject.get("objCod_objBase").getAsString());
        txtCNPJ.setText(objJsonObject.get("cnpj_fab").getAsString());
    }

    private void controlaAcesso(boolean status) {
        btnIncluir.setEnabled(status);
        btnSalvar.setEnabled(!status);
        btnExcluir.setEnabled(status);
        btnAlterar.setEnabled(status);
        btnCancelar.setEnabled(!status);
        txtNomeFab.setEditable(!status);
        txtCNPJ.setEditable(!status);
        btnPrimeiro.setEnabled(status);
        btnAnterior.setEnabled(status);
        btnProximo.setEnabled(status);
        btnUltimo.setEnabled(status);
        txtCodigo.setEnabled(status);
    }

    private void limpaTelaCompleta() {
        txtNomeFab.setText("");
        txtCNPJ.setText("");
        txtCodigo.setText("");
    }

    private void atualizaTela() {
        ControllerBaseCtrl ctrlSol = new CtrlSolicitante();
        int codigoCli = Integer.parseInt(txtCodigo.getText());
        String json;
        json = ctrlSol.Recuperar(codigoCli);
        limpaTelaCompleta();
        if (!json.isEmpty()) {
            setJsonTelaFabricante(json);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jLabelCRM = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        txtNomeFab = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fabricante");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Codigo:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/logo_mini.png"))); // NOI18N

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/first_mini.png"))); // NOI18N
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/previous_mini.png"))); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/next_mini.png"))); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/last_mini.png"))); // NOI18N
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnUltimo)
                        .addComponent(btnProximo))
                    .addComponent(btnAnterior)
                    .addComponent(btnPrimeiro)))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/create.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/trash.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/close.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/back.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(176, 176, 176))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnIncluir, btnSalvar, jButton2});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnIncluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnIncluir, btnSalvar, jButton2});

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCNPJKeyPressed(evt);
            }
        });

        jLabelCRM.setText("CNPJ:");

        jLabelNome.setText("Razão Social:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCRM)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeFab)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeFab, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCRM)
                    .addComponent(txtCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelCRM, jLabelNome, txtCNPJ, txtNomeFab});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        txtNomeFab.requestFocus();
        controlaAcesso(false);
        isAlterar = false;
        if (!txtCodigo.getText().isEmpty()) {
            codBackup = Integer.parseInt(txtCodigo.getText());
        }
        limpaTelaCompleta();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            //System.out.println("Solicitante: " + toJsonCliente());
            CtrlFabricante CTRLFab = new CtrlFabricante();
            int codigoSol = CTRLFab.Salvar(toJsonFabricante());
            txtCodigo.setText(String.valueOf(codigoSol));
            Mensagem.information("Fabricante cadastrado com sucesso", this);
            //atualizaTela();
            controlaAcesso(true);
        } catch (Exception ex) {
            Mensagem.error("Não foi possivel cadastrar o fabricante", this);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        controlaAcesso(false);
        isAlterar = true;
        if (!txtCodigo.getText().isEmpty()) {
            codBackup = Integer.parseInt(txtCodigo.getText());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int codigo = txtCodigo.getText().isEmpty() ? 0 : Integer.parseInt(txtCodigo.getText());
        if (codigo > 0) {
            if (Mensagem.confirm("Deseja excluir o fabricante selecionado ?", this)) {
                objCtrlFab.Deletar(codigo);
                Mensagem.information("Fabricante excluido com sucesso", this);
                limpaTelaCompleta();

                setJsonTelaFabricante(new CtrlFabricante().RecuperaRegistroAnterior(codigo));
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (!Mensagem.confirm("Deseja descartar as alterações?", this)) {
            return;
        }
        controlaAcesso(true);
        CtrlFabricante CTRLFab = new CtrlFabricante();
        if (!isAlterar) {
            setJsonTelaFabricante(CTRLFab.Recuperar(codBackup));
        } else {
            setJsonTelaFabricante(CTRLFab.Recuperar(Integer.parseInt(txtCodigo.getText())));
        }
        codBackup = -1;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        txtCodigo.selectAll();
    }//GEN-LAST:event_txtCodigoFocusGained

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            ControllerBaseCtrl ctrlFab = new CtrlFabricante();
            int codigoCli = Integer.parseInt(txtCodigo.getText());
            String json;
            //limpaTelaCompleta();
            if (codigoCli > 0) { //Pesquisa direta
                json = ctrlFab.Recuperar(codigoCli);

                if (json.isEmpty()) {
                    if (Mensagem.confirm("Fabricante não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                        Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "FABRICANTE", new String());
                        pesq.setVisible(true);
                        //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                        setJsonTelaFabricante(new CtrlFabricante().RecuperarFabCNPJ(pesq.getResultPesq()));
                    }
                } else {
                    setJsonTelaFabricante(json);
                    controlaAcesso(true);
                }
            } else { //Abre a tela de pesquisa

            }
        } catch (NumberFormatException ex) {
            txtCodigo.requestFocus();

        } catch (Exception ex) {
            Mensagem.warning(ex.getMessage(), this);
        } finally {
            txtCodigo.selectAll();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == 10) {
            btnPesquisarActionPerformed(new java.awt.event.ActionEvent(this, WIDTH, "Salvar"));
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlFabricante objCtrlFab = new CtrlFabricante();
            String Fabricante = objCtrlFab.RecuperaPrimeiroRegistro();
            if (Fabricante == null) {
                Mensagem.information("Erro ao recuperar o primeiro registro !!!", this);
                return;
            }

            setJsonTelaFabricante(Fabricante);
        }
    }//GEN-LAST:event_btnPrimeiroActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlFabricante objCtrlFab = new CtrlFabricante();
            String Fabricante = objCtrlFab.RecuperaRegistroAnterior(Integer.parseInt(txtCodigo.getText()));
            if (Fabricante == null) {
                Mensagem.information("Este é o primeiro registro !!!", this);
                return;
            }

            setJsonTelaFabricante(Fabricante);
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlFabricante objCtrlFab = new CtrlFabricante();
            String Fabricante = objCtrlFab.RecuperaProximoRegistro(Integer.parseInt(txtCodigo.getText()));
            if (Fabricante == null) {
                Mensagem.information("Este é o último registro !!!", this);
                return;
            }

            setJsonTelaFabricante(Fabricante);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        if (!txtCodigo.getText().isEmpty()) {
            CtrlFabricante objCtrlFab = new CtrlFabricante();
            String Fabricante = objCtrlFab.RecuperaUltimoRegistro();
            if (Fabricante == null) {
                Mensagem.information("Erro ao recuperar o último registro !!!", this);
                return;
            }

            setJsonTelaFabricante(Fabricante);
        }
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void txtCNPJKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCNPJKeyPressed
        if (!txtCNPJ.isEditable()) {
            return;
        }

        if ((evt.getKeyCode() >= 33 && evt.getKeyCode() <= 40) || evt.getKeyCode() == 127 || evt.getKeyCode() == 8 || evt.getKeyCode() == 10) {
            return;
        }

        /*if (evt.getKeyCode() == 10) {
        btnSalvarActionPerformed(new java.awt.event.ActionEvent(this, 0, "Salvar"));
        }*/
        if (!Character.isDigit(evt.getKeyChar())) {
            String texto = txtCNPJ.getText();
            int tamanho = texto.length();
            txtCNPJ.setText(texto.substring(0, tamanho));
            Mensagem.warning("Informe apenas números!!!", this);//System.out.println("Digito");
            return;
        }

    }//GEN-LAST:event_txtCNPJKeyPressed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            Fabricante dialog = new Fabricante(new javax.swing.JFrame(), true, -1);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomeFab;
    // End of variables declaration//GEN-END:variables
}
