/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CtrlCliente;
import Controller.CtrlLote;
import Controller.CtrlPedido;
import Controller.CtrlProduto;
import Controller.CtrlSolicitante;
import Controller.CtrlUsuario;
import View.Mensagens.Mensagem;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abner Amorim
 */
public class Pesquisa_Atendimento extends javax.swing.JDialog {

    private DefaultTableModel ModeloTab;

    private String tipoPesq;
    private String[] dadosRegSelec; //guarda os dados do ultimo registro selecionado
    private List<Object[]> arListProd;
    private ArrayList<Integer> arIndexProds; //guarda os codigos dos pedidos que estão pr ser inseridos no pedido
    private String retorno;
    private String txtPesqAnterior;
    private JsonParser parser = new JsonParser();
    private JsonObject produto_BKP;
    private JsonObject solicitante_BKP;
    private JsonObject lote_BKP;
    private JsonObject responsavel_BKP;
    private JsonObject cliente_BKP;
    private int codigo;
    private String login;

    public int getCodigo() {
        return codigo;
    }

    /**
     * Creates new form PesquisaView
     *
     * @param parent
     * @param modal
     * @param retorno
     */
    public Pesquisa_Atendimento(java.awt.Frame parent, boolean modal, String retorno, String pResponsavel) {
        super(parent, modal);
        this.retorno = retorno;
        login = pResponsavel;
        //System.out.println("entrou na tela de pesquisa  - tipopesq: " + TipoPesq);
        initComponents();
        Util.Util.temaVisualizacao(this);
        arListProd = new ArrayList<>();
        arIndexProds = new ArrayList<>();
        jckEmTodaParte.setSelected(true);
        txtCliente.setEditable(true);
        ModeloTab = (DefaultTableModel) tabResutPesq.getModel();
        txtPesqAnterior = "";
        habilitaDuploCliqueTabela();
        limparLinhasTabela();
        txtDataInicio.requestFocus();
        new CtrlSolicitante().Recuperar(1);
    }

    private void limparLinhasTabela() {
        ModeloTab.setNumRows(0);
    }

    public String getResultPesq() {
        return retorno;
    }

    private void habilitaDuploCliqueTabela() {
        tabResutPesq.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    if (retorno == null) {
                        btnSelecionarActionPerformed(new ActionEvent(this, 0, "BUSCAR"));
                    } else {
                        btnSelecionarActionPerformed(new ActionEvent(this, 0, "RETORNAR"));
                    }
                }
            }
        });
    }
    
    private String dateFormatBanco(String pDate) {
        Date data = new Date();
        data.setTime(Date.parse(pDate));
        //System.out.println("data: " + data.toString());
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-dd-MM");
        //System.out.println("data: " + formatador.format(data));
        return formatador.format(data);
    }

    private String dateFormatBanco(Date pDate) {
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-dd-MM");
        return formatador.format(pDate);
    }
    
    private Date dateFormatDate(String pDate) {
        Date data = new Date();
        data.setTime(Date.parse(pDate.split("/")[1] + "/" + pDate.split("/")[0] + "/" + pDate.split("/")[2]));
        //System.out.println("Data: " + data.toString());
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnSelecionar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabResutPesq = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnBuscarSolicitante = new javax.swing.JButton();
        txtSolicitante = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btnBuscarProduto = new javax.swing.JButton();
        txtProduto = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtResponsavel = new javax.swing.JTextField();
        btnBuscarResponsavel = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        txtDataInicio = new javax.swing.JFormattedTextField();
        labelData = new javax.swing.JLabel();
        txtDataFim = new javax.swing.JFormattedTextField();
        labelData3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtLote = new javax.swing.JTextField();
        btnBuscarLote = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JFormattedTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        txtCuidados = new javax.swing.JTextField();
        jckEmTodaParte = new javax.swing.JCheckBox();
        jlNumResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/back.png"))); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/marcada.png"))); // NOI18N
        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSelecionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnCancelar, btnSelecionar});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/logo_mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap())
        );

        tabResutPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Data", "Responsável", "Cliente", "Solicitante", "Cuidados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabResutPesq.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabResutPesq.getTableHeader().setReorderingAllowed(false);
        tabResutPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabResutPesqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabResutPesq);
        if (tabResutPesq.getColumnModel().getColumnCount() > 0) {
            tabResutPesq.getColumnModel().getColumn(0).setResizable(false);
            tabResutPesq.getColumnModel().getColumn(0).setPreferredWidth(50);
            tabResutPesq.getColumnModel().getColumn(1).setResizable(false);
            tabResutPesq.getColumnModel().getColumn(1).setPreferredWidth(90);
            tabResutPesq.getColumnModel().getColumn(2).setResizable(false);
            tabResutPesq.getColumnModel().getColumn(2).setPreferredWidth(90);
            tabResutPesq.getColumnModel().getColumn(3).setResizable(false);
            tabResutPesq.getColumnModel().getColumn(3).setPreferredWidth(230);
            tabResutPesq.getColumnModel().getColumn(4).setResizable(false);
            tabResutPesq.getColumnModel().getColumn(4).setPreferredWidth(200);
            tabResutPesq.getColumnModel().getColumn(5).setResizable(false);
            tabResutPesq.getColumnModel().getColumn(5).setPreferredWidth(250);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Solicitante"));

        btnBuscarSolicitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnBuscarSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSolicitanteActionPerformed(evt);
            }
        });

        txtSolicitante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLimpaDescricao(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSolicitanteFocusLost(evt);
            }
        });
        txtSolicitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSolicitanteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLimpaCharsInval(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(txtSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscarSolicitante, txtSolicitante});

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        btnBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        txtProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLimpaDescricao(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtProdutoFocusLost(evt);
            }
        });
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLimpaCharsInval(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Responsável"));

        txtResponsavel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLimpaDescricao(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtResponsavelFocusLost(evt);
            }
        });
        txtResponsavel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtResponsavelKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLimpaCharsInval(evt);
            }
        });

        btnBuscarResponsavel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnBuscarResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarResponsavelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnBuscarResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel8Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBuscarResponsavel, txtResponsavel});

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Período"));

        try {
            txtDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                limpaDataVazia(evt);
            }
        });

        labelData.setText("Início:");

        try {
            txtDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataFim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                limpaDataVazia(evt);
            }
        });

        labelData3.setText("Fim:");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addComponent(labelData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelData3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataFim))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelData)
                        .addComponent(labelData3))
                    .addComponent(txtDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelData, labelData3, txtDataFim, txtDataInicio});

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Lote"));

        txtLote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLimpaDescricao(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLoteFocusLost(evt);
            }
        });
        txtLote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLoteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLimpaCharsInval(evt);
            }
        });

        btnBuscarLote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnBuscarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLoteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(txtLote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscarLote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        try {
            txtCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("# ### #### ###### ## #")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCliente.setToolTipText("");
        txtCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtClienteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClienteFocusLost(evt);
            }
        });
        txtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtClienteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLimpaCharsInval(evt);
            }
        });

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuidados"));

        txtCuidados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuidadosKeyReleased(evt);
            }
        });

        jckEmTodaParte.setText("Em toda parte");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(txtCuidados, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jckEmTodaParte)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jckEmTodaParte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(txtCuidados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(5, 5, 5))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel11, jPanel4, jPanel7, jPanel8});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlNumResult.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jlNumResult, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jlNumResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        if (tabResutPesq.getRowCount() == 0) {
            return;
        }
        int codigoObjeto = Integer.parseInt(ModeloTab.getValueAt(tabResutPesq.getSelectedRow(), 0).toString());
        if(retorno == null){
                    new Pedido(new Frame(), true, login, codigoObjeto).setVisible(true);
                } else {
                    retorno = tabResutPesq.getValueAt(tabResutPesq.getSelectedRow(), 1).toString();
                    this.codigo = Integer.parseInt(tabResutPesq.getValueAt(tabResutPesq.getSelectedRow(), 0).toString());
                    //System.out.println("Retorno na tela de pesquisa: " + retorno);
                    this.dispose();
                }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tabResutPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabResutPesqMouseClicked

    }//GEN-LAST:event_tabResutPesqMouseClicked

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String cliente = new CtrlCliente().RecuperarCliCompCartao(txtCliente.getText().substring(0, 22));
        if (cliente.equals("Erro ao recuperar o Cliente !!!")) {
            if (evt.getActionCommand().isEmpty() && Mensagem.confirm("Cliente não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "CLIENTE", new String());
                pesq.setVisible(true);
                //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                String retorno = pesq.getResultPesq();
                if (retorno == null || retorno.equals("")) {
                    return;
                }
                cliente_BKP = parser.parse(new CtrlCliente().RecuperarCliCompCartao(retorno)).getAsJsonObject();
                txtCliente.setText(retorno);
                txtCuidados.requestFocus();
            }
        } else {
            cliente_BKP = parser.parse(cliente).getAsJsonObject();
            //txtCliente.setText(cliente_BKP.get("cartao_cli").getAsString() + " - " + cliente_BKP.get("nome_cli").getAsString());
            txtCuidados.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSolicitanteActionPerformed
        if (txtSolicitante.getText().isEmpty()) {
            return;
        }
        String solicitante = new CtrlSolicitante().RecuperarSolCRM(txtSolicitante.getText().split(" ")[0]);
        //System.out.println("Solicitante recuperado: " + solicitante);
        if (solicitante == null) {
            if (evt.getActionCommand().isEmpty() && Mensagem.confirm("Solicitante não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "SOLICITANTE", new String());
                pesq.setVisible(true);
                //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                String retorno = pesq.getResultPesq();
                if (retorno == null || retorno.equals("")) {
                    return;
                }
                solicitante_BKP = parser.parse(new CtrlSolicitante().RecuperarSolCRM(retorno)).getAsJsonObject();
                txtSolicitante.setText(solicitante_BKP.get("crm_sol").getAsString() + " - " + solicitante_BKP.get("nome_sol").getAsString());
                txtLote.requestFocus();
            }
        } else {
            solicitante_BKP = parser.parse(solicitante).getAsJsonObject();
            txtSolicitante.setText(solicitante_BKP.get("crm_sol").getAsString() + " - " + solicitante_BKP.get("nome_sol").getAsString());
            txtLote.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarSolicitanteActionPerformed

    private void btnBuscarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLoteActionPerformed
        if (txtLote.getText().isEmpty()) {
            return;
        }
        String lote = new CtrlLote().RecuperarLote(txtLote.getText().split(" ")[0]);
        if (lote == null) {
            if (evt.getActionCommand().isEmpty() && Mensagem.confirm("Lote não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "LOTE", new String());
                pesq.setVisible(true);
                //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                String retorno = pesq.getResultPesq();
                if (retorno == null || retorno.equals("")) {
                    return;
                }
                lote_BKP = parser.parse(new CtrlLote().RecuperarLote(retorno)).getAsJsonObject();
                txtLote.setText(lote_BKP.get("lote").getAsString() + " - " + lote_BKP.get("produtoIdent").getAsString());
                txtResponsavel.requestFocus();
            }
        } else {
            lote_BKP = parser.parse(lote).getAsJsonObject();
            txtLote.setText(lote_BKP.get("lote").getAsString() + " - " + lote_BKP.get("produtoIdent").getAsString());
            txtResponsavel.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarLoteActionPerformed

    private void btnBuscarResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarResponsavelActionPerformed
        if (txtResponsavel.getText().isEmpty()) {
            return;
        }
        String responsavel = new CtrlUsuario().SelecionaPorLogin(txtResponsavel.getText().split(" ")[0]);
        if (responsavel == null) {
            if (evt.getActionCommand().isEmpty() && Mensagem.confirm("Usuário não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "USUARIO", new String());
                pesq.setVisible(true);
                //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                String retorno = pesq.getResultPesq();
                if (retorno == null || retorno.equals("")) {
                    return;
                }
                responsavel_BKP = parser.parse(new CtrlUsuario().Recuperar(pesq.getCodigo())).getAsJsonObject();
                txtResponsavel.setText(responsavel_BKP.get("login_usu").getAsString() + " - " + responsavel_BKP.get("nome_usu").getAsString());
                txtCliente.requestFocus();
            }
        } else {
            responsavel_BKP = parser.parse(responsavel).getAsJsonObject();
            txtResponsavel.setText(responsavel_BKP.get("login_usu").getAsString() + " - " + responsavel_BKP.get("nome_usu").getAsString());
            txtCliente.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarResponsavelActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        //System.out.println("evt: " + evt.getActionCommand().isEmpty());
        if (txtProduto.getText().isEmpty()) {
            return;
        }
        String insumo = new CtrlProduto().RecuperarProdIdentificador(txtProduto.getText().split(" ")[0]);
        if (insumo == null) {
            if (evt.getActionCommand().isEmpty() && Mensagem.confirm("Insumo não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "PRODUTO", new String());
                pesq.setVisible(true);
                //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                String retorno = pesq.getResultPesq();
                if (retorno == null || retorno.equals("")) {
                    return;
                }
                produto_BKP = parser.parse(new CtrlProduto().RecuperarProdIdentificador(retorno)).getAsJsonObject();
                txtProduto.setText(produto_BKP.get("identificador_prod").getAsString() + " - " + produto_BKP.get("descricao_prod").getAsString());
                txtSolicitante.requestFocus();
            }
        } else {
            produto_BKP = parser.parse(insumo).getAsJsonObject();
            txtProduto.setText(produto_BKP.get("identificador_prod").getAsString() + " - " + produto_BKP.get("descricao_prod").getAsString());
            txtSolicitante.requestFocus();
        }
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String dataInicio = txtDataInicio.getText();
        String dataFim = txtDataFim.getText();
        String produto = txtProduto.getText().split(" ")[0];
        String solicitante = txtSolicitante.getText().split(" ")[0];
        String lote = txtLote.getText().split(" ")[0];
        String responsavel = txtResponsavel.getText().split(" ")[0];
        String cliente = txtCliente.getText();
        String cuidados = txtCuidados.getText();
        
        if (dataInicio.isEmpty() && dataFim.isEmpty()
                && produto.isEmpty() && solicitante.isEmpty()
                && lote.isEmpty() && responsavel.isEmpty()
                && cliente.isEmpty() && cuidados.isEmpty()) {
            Mensagem.error("Informe algum campo para realizar a busca", this);
        }
        
        if(jckEmTodaParte.isSelected() && !cuidados.isEmpty()){
            cuidados = "%" + cuidados + "%";
        }
        //boolean isPreenchido = false;
        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
        if (dataInicio.equals("  /  /    ") ^ dataFim.equals("  /  /    ")) {
            if (!dataInicio.equals("  /  /    ")) {
                Date dataInicioDate = dateFormatDate(dataInicio);
                dataInicio = formatador.format(dataInicioDate);
                dataFim = formatador.format(new Date());
            } else {
                Date umAnoAtras = new Date();
                umAnoAtras.setDate(new Date().getDate() - 366);
                dataInicio = formatador.format(umAnoAtras);
                dataFim = formatador.format(dateFormatDate(dataFim));
            }
        } else if (!dataInicio.equals("  /  /    ") && !dataFim.equals("  /  /    ")) {
            Date dataInicioDate = dateFormatDate(dataInicio);
            Date dataFimDate = dateFormatDate(dataFim);
            dataInicio = formatador.format(dataInicioDate);
            dataFim = formatador.format(dataFimDate);
        } else if (dataInicio.equals("  /  /    ") && dataFim.equals("  /  /    ")) {
            dataInicio = "";
            dataFim = "";
        }
        //System.out.println("dateFormatBanco (dataFim): " + dataFim + " - (dataInicio): " + dataInicio);
        List<String[]> pedidos = new CtrlPedido().SelecionarPorCampo_List(dataInicio, dataFim, produto, solicitante, lote, responsavel, cliente, cuidados);
        int size = pedidos.size();
        ModeloTab.setNumRows(0);
        if(size == 0){
            Mensagem.information("Não foram encontrados resultados\nPara os parâmetros informados !!", this);
            jlNumResult.setText("0 Resultado Encontrado");
            return;
        }
        
        for (int i = 0; i < size; i++) {
            //System.out.println(pedidos.get(i)[1].split("-")[2]+"/"+pedidos.get(i)[1].split("-")[1]+"/"+pedidos.get(i)[1].split("-")[0] + " data_normal: " + pedidos.get(i)[1]);
            ModeloTab.addRow(new String[]{pedidos.get(i)[0], pedidos.get(i)[1].split("-")[2]+"/"+pedidos.get(i)[1].split("-")[1]+"/"+pedidos.get(i)[1].split("-")[0], pedidos.get(i)[2], pedidos.get(i)[3], pedidos.get(i)[4], pedidos.get(i)[5]});
        }
        if(size == 1)
            jlNumResult.setText("1 Resultado Encontrado");
        else
            jlNumResult.setText(size + " Resultados Encontrados");
            
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCuidadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuidadosKeyReleased
        /*if (evt.getKeyCode() == 10) {
            ModeloTab.setNumRows(0);
            buscaRegistrosPesquisa();
        }*/
    }//GEN-LAST:event_txtCuidadosKeyReleased

    private void txtLimpaDescricao(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLimpaDescricao
        JTextField txt = (JTextField) evt.getComponent();
        String txtAntigo = txt.getText();
        if (txtAntigo.isEmpty() || txtAntigo.replace(" ", "").isEmpty()) {
            return;
        }
        //System.out.println("txtAntigo: " + txtAntigo + " size: " + txtAntigo.length());
        txt.setText(txtAntigo.split(" ")[0]);
    }//GEN-LAST:event_txtLimpaDescricao

    private void txtProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProdutoFocusLost
        if (txtProduto.getText().isEmpty()) {
            return;
        }
        btnBuscarProdutoActionPerformed(new ActionEvent(this, 0, "Buscar"));
        /*String produto_String = new CtrlProduto().RecuperarProdIdentificador(txtProduto.getText().split(" ")[0]);
        if(produto_String == null){
        if(produto_BKP == null){
        txtProduto.setText("");
        return;
        }
        //txtProduto.setText(produto_BKP.get("identificador_prod").getAsString() + " - " + produto_BKP.get("descricao_prod").getAsString());
        } else {
        JsonObject produto_Buscado = parser.parse(produto_String).getAsJsonObject();
        txtProduto.setText(produto_Buscado.get("identificador_prod").getAsString() + " - " + produto_Buscado.get("descricao_prod").getAsString());
        produto_BKP = produto_Buscado;
        }*/
    }//GEN-LAST:event_txtProdutoFocusLost

    private void txtLimpaCharsInval(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLimpaCharsInval
        JTextField txt = (JTextField) evt.getComponent();
        txt.setText(txt.getText().replace("-", "").replace(" ", ""));
    }//GEN-LAST:event_txtLimpaCharsInval

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        if (evt.getKeyCode() == 10) {
            btnBuscarProdutoActionPerformed(new ActionEvent(this, 0, "buscar"));
        }
    }//GEN-LAST:event_txtProdutoKeyPressed

    private void txtSolicitanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSolicitanteFocusLost
        if (txtSolicitante.getText().isEmpty()) {
            return;
        }
        btnBuscarSolicitanteActionPerformed(new ActionEvent(this, 0, "Buscar"));
        /*String Solicitante_String = new CtrlSolicitante().RecuperarSolCRM(txtSolicitante.getText().split(" ")[0]);
        System.out.println("Solicitante recuperado: " + Solicitante_String);
        if(Solicitante_String == null){
        if(solicitante_BKP == null){
        //txtSolicitante.setText("");
        return;
        }
        //txtSolicitante.setText(solicitante_BKP.get("crm_sol").getAsString() + " - " + solicitante_BKP.get("nome_sol").getAsString());
        } else {
        JsonObject solicitante_Buscado = parser.parse(Solicitante_String).getAsJsonObject();
        txtSolicitante.setText(solicitante_Buscado.get("crm_sol").getAsString() + " - " + solicitante_Buscado.get("nome_sol").getAsString());
        solicitante_BKP = solicitante_Buscado;
        }*/
    }//GEN-LAST:event_txtSolicitanteFocusLost

    private void txtSolicitanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSolicitanteKeyPressed
        if (evt.getKeyCode() == 10) {
            btnBuscarSolicitanteActionPerformed(new ActionEvent(this, 0, "buscar"));
        }
    }//GEN-LAST:event_txtSolicitanteKeyPressed

    private void txtLoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoteKeyPressed
        if (evt.getKeyCode() == 10) {
            btnBuscarLoteActionPerformed(new ActionEvent(this, 0, "buscar"));
        }
    }//GEN-LAST:event_txtLoteKeyPressed

    private void txtLoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLoteFocusLost
        if (txtLote.getText().isEmpty()) {
            return;
        }
        btnBuscarLoteActionPerformed(new ActionEvent(this, 0, "Buscar"));
        /*String lote_String = new CtrlSolicitante().RecuperarSolCRM(txtLote.getText().split(" ")[0]);
        if(lote_String == null){
        if(lote_BKP == null){
        txtLote.setText("");
        return;
        }
        //txtLote.setText(lote_BKP.get("lote").getAsString() + " - " + lote_BKP.get("produtoIdent").getAsString());
        } else {
        JsonObject lote_Buscado = parser.parse(lote_String).getAsJsonObject();
        txtLote.setText(lote_Buscado.get("lote").getAsString() + " - " + lote_Buscado.get("produtoIdent").getAsString());
        lote_BKP = lote_Buscado;
        }*/
    }//GEN-LAST:event_txtLoteFocusLost

    private void txtResponsavelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResponsavelFocusLost
        if (txtResponsavel.getText().isEmpty()) {
            return;
        }
        btnBuscarResponsavelActionPerformed(new ActionEvent(this, 0, "Buscar"));
        /*String responsavel_String = new CtrlUsuario().SelecionaPorLogin(txtResponsavel.getText().split(" ")[0]);
        if(responsavel_String == null){
        if(responsavel_BKP == null){
        txtResponsavel.setText("");
        return;
        }
        //txtResponsavel.setText(responsavel_BKP.get("login_usu").getAsString() + " - " + responsavel_BKP.get("nome_usu").getAsString());
        } else {
        JsonObject responsavel_Buscado = parser.parse(responsavel_String).getAsJsonObject();
        txtResponsavel.setText(responsavel_Buscado.get("login_usu").getAsString() + " - " + responsavel_Buscado.get("nome_usu").getAsString());
        responsavel_BKP = responsavel_Buscado;
        }*/
    }//GEN-LAST:event_txtResponsavelFocusLost

    private void txtResponsavelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResponsavelKeyPressed
        if (evt.getKeyCode() == 10) {
            btnBuscarResponsavelActionPerformed(new ActionEvent(this, 0, "buscar"));
        }
    }//GEN-LAST:event_txtResponsavelKeyPressed

    private void txtClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusLost
        if (txtCliente.getText().equals("                      ")) {
            txtCliente.setValue("");
            return;
        }
        btnBuscarClienteActionPerformed(new ActionEvent(this, 0, "Buscar"));
        /*String cliente_String = new CtrlCliente().RecuperarCliCompCartao(txtCliente.getText().substring(0, 22));
        if(cliente_String.equals("Erro ao recuperar o Cliente !!!")){
        if(cliente_BKP == null){
        txtCliente.setText("");
        return;
        }
        //txtResponsavel.setText(responsavel_BKP.get("login_usu").getAsString() + " - " + responsavel_BKP.get("nome_usu").getAsString());
        } else {
        JsonObject cliente_Buscado = parser.parse(cliente_String).getAsJsonObject();
        txtCliente.setText(cliente_Buscado.get("cartao_cli").getAsString() + " - " + cliente_Buscado.get("nome_cli").getAsString());
        cliente_BKP = cliente_Buscado;
        }*/
    }//GEN-LAST:event_txtClienteFocusLost

    private void txtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClienteKeyPressed
        if (evt.getKeyCode() == 10) {
            btnBuscarClienteActionPerformed(new ActionEvent(this, 0, "buscar"));
        }
    }//GEN-LAST:event_txtClienteKeyPressed

    private void txtClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClienteFocusGained
        JTextField txt = (JTextField) evt.getComponent();
        String txtAntigo = txt.getText();
        if (txtAntigo.equals("                      ")) {
            return;
        }
        //System.out.println("txtAntigo: " + txtAntigo + " size: " + txtAntigo.length());
        txt.setText(txtAntigo.substring(0, 22));
    }//GEN-LAST:event_txtClienteFocusGained

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void limpaDataVazia(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_limpaDataVazia
        JFormattedTextField txt = (JFormattedTextField) evt.getComponent();
        if (txt.getText().equals("  /  /    ")) {
            txt.setValue("");
        }
    }//GEN-LAST:event_limpaDataVazia

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            //Pedido dialog = new Pedido(new javax.swing.JFrame(), true, );
            Pesquisa_Atendimento dialog = new Pesquisa_Atendimento(new javax.swing.JFrame(), true, null, "teste");
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarLote;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnBuscarResponsavel;
    private javax.swing.JButton btnBuscarSolicitante;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jckEmTodaParte;
    private javax.swing.JLabel jlNumResult;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelData3;
    private javax.swing.JTable tabResutPesq;
    private javax.swing.JFormattedTextField txtCliente;
    private javax.swing.JTextField txtCuidados;
    private javax.swing.JFormattedTextField txtDataFim;
    private javax.swing.JFormattedTextField txtDataInicio;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextField txtSolicitante;
    // End of variables declaration//GEN-END:variables
}
