/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerBaseCtrl;
import Controller.CtrlSolicitante;
import View.Mensagens.Mensagem;
import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonPrimitive;

/**
 *
 * @author Abner Amorim
 */
public class Solicitante extends javax.swing.JDialog {

    /**
     * Creates new form CadastroCliente
     */
    private JsonParser objParser;
    private JsonObject objJsonObject;
    private boolean isAlterar;
    private Gson objGson;
    private ControllerBaseCtrl objCtrlSol;
    private int codBackup = -1;

    public Solicitante(java.awt.Frame parent, boolean modal, int pCodigoInicial) {
        super(parent, modal);
        initComponents();
        Util.Util.temaVisualizacao(this);
        objParser = new JsonParser();
        objGson = new Gson();
        objCtrlSol = new CtrlSolicitante();
        if (pCodigoInicial > 0) {
            setJsonTelaSolicitante(objCtrlSol.Recuperar(pCodigoInicial));
        } else {
            setJsonTelaSolicitante(objCtrlSol.RecuperaPrimeiroRegistro());
        }
        isAlterar = false;
        controlaAcesso(true);
    }

    public String toJsonSolicitante() throws Exception {
        objJsonObject = new JsonObject();

        objJsonObject.add("nome_sol", new JsonPrimitive(txtNome.getText()));
        objJsonObject.add("crm_sol", new JsonPrimitive(txtCRM.getText()));

        if (isAlterar) {
            objJsonObject.add("objCod_objBase", new JsonPrimitive(Integer.parseInt(txtCodigo.getText())));
        }

        //System.out.println(new Gson().toJson(objJsonObject));
        return new Gson().toJson(objJsonObject);
    }

    public void setJsonTelaSolicitante(String json) {
        if (json == null || json.isEmpty()) {
            return;
        }

        objJsonObject = objParser.parse(json).getAsJsonObject();
        txtNome.setText(objJsonObject.get("nome_sol").getAsString());
        txtCodigo.setText(objJsonObject.get("objCod_objBase").getAsString());
        txtCRM.setText(objJsonObject.get("crm_sol").getAsString());
    }

    private void controlaAcesso(boolean status) {
        btnIncluir.setEnabled(status);
        btnSalvar.setEnabled(!status);
        btnExcluir.setEnabled(status);
        btnAlterar.setEnabled(status);
        btnCancelar.setEnabled(!status);
        txtNome.setEditable(!status);
        txtCRM.setEditable(!status);
        btnPrimeiroSolicitante.setEnabled(status);
        btnAnteriorSolicitante.setEnabled(status);
        btnProximoSolicitante.setEnabled(status);
        btnUltimoSolicitante.setEnabled(status);
        txtCodigo.setEnabled(status);
    }

    private void limpaTelaCompleta() {
        txtNome.setText("");
        txtCRM.setText("");
        txtCodigo.setText("");
    }

    private void atualizaTela() {
        ControllerBaseCtrl ctrlSol = new CtrlSolicitante();
        int codigoCli = Integer.parseInt(txtCodigo.getText());
        String json;
        json = ctrlSol.Recuperar(codigoCli);
        limpaTelaCompleta();
        if (!json.isEmpty()) {
            setJsonTelaSolicitante(json);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        btnProximoSolicitante = new javax.swing.JButton();
        btnAnteriorSolicitante = new javax.swing.JButton();
        btnPrimeiroSolicitante = new javax.swing.JButton();
        btnUltimoSolicitante = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtCRM = new javax.swing.JTextField();
        jLabelCRM = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Médico Solicitante");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(277, 80));

        jLabel1.setText("Codigo:");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoKeyPressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/logo_mini.png"))); // NOI18N

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/search.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnProximoSolicitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/next_mini.png"))); // NOI18N
        btnProximoSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoSolicitanteActionPerformed(evt);
            }
        });

        btnAnteriorSolicitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/previous_mini.png"))); // NOI18N
        btnAnteriorSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorSolicitanteActionPerformed(evt);
            }
        });

        btnPrimeiroSolicitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/first_mini.png"))); // NOI18N
        btnPrimeiroSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroSolicitanteActionPerformed(evt);
            }
        });

        btnUltimoSolicitante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/last_mini.png"))); // NOI18N
        btnUltimoSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoSolicitanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPrimeiroSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnAnteriorSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProximoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(btnUltimoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnUltimoSolicitante)
                    .addComponent(btnProximoSolicitante)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnAnteriorSolicitante)
                        .addComponent(btnPrimeiroSolicitante)))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/check.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/create.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/trash.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/close.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/back.png"))); // NOI18N
        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(176, 176, 176))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnIncluir, btnSalvar, jButton2});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnIncluir)
                    .addComponent(btnSalvar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnIncluir, btnSalvar, jButton2});

        txtCRM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCRMFocusLost(evt);
            }
        });
        txtCRM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCRMKeyPressed(evt);
            }
        });

        jLabelCRM.setText("CRM - MG:");

        jLabelNome.setText("Dr./Dra.:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCRM)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtCRM))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCRM)
                    .addComponent(txtCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabelCRM, jLabelNome, txtCRM, txtNome});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        txtNome.requestFocus();
        controlaAcesso(false);
        isAlterar = false;
        if(!txtCodigo.getText().isEmpty())
            codBackup = Integer.parseInt(txtCodigo.getText());
        limpaTelaCompleta();
        //System.out.println("Codbkp: " + codBackup);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        try {
            //System.out.println("Solicitante: " + toJsonCliente());
            CtrlSolicitante CTRLSol = new CtrlSolicitante();
            int codigoSol = CTRLSol.Salvar(toJsonSolicitante());
            txtCodigo.setText(String.valueOf(codigoSol));
            Mensagem.information("Solicitante cadastrado com sucesso", this);
            //atualizaTela();
            controlaAcesso(true);
        } catch (Exception ex) {
            Mensagem.error("Não foi possivel cadastrar o solicitante", this);
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        controlaAcesso(false);
        if(!txtCodigo.getText().isEmpty())
            codBackup = Integer.parseInt(txtCodigo.getText());
        isAlterar = true;
        //System.out.println("Codbkp: " + codBackup);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if(!Mensagem.confirm("Deseja excluir este Solicitante?", this)){
            return;
        }
        int codigo = txtCodigo.getText().isEmpty() ? 0 : Integer.parseInt(txtCodigo.getText());
        if (codigo > 0) {
            objCtrlSol.Deletar(codigo);
            Mensagem.information("Solicitante excluido com sucesso", this);
            limpaTelaCompleta();
            setJsonTelaSolicitante(new CtrlSolicitante().RecuperaRegistroAnterior(codigo));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(!Mensagem.confirm("Deseja descartar as alterações?", this)){
            //System.out.println("não descarta");
            return;
        }
        controlaAcesso(true);
        CtrlSolicitante CtrlSol = new CtrlSolicitante();
        if (codBackup > 0) {
            //System.out.println("codbackup > 0 : " + codBackup);
            setJsonTelaSolicitante(CtrlSol.Recuperar(codBackup));
        } else {
            //System.out.println("codbackup <= 0");
            setJsonTelaSolicitante(CtrlSol.Recuperar(Integer.parseInt(txtCodigo.getText())));
        }
        //System.out.println("cancelar Codbkp: " + codBackup);
        codBackup = -1;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained
        txtCodigo.selectAll();
    }//GEN-LAST:event_txtCodigoFocusGained

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            CtrlSolicitante ctrlSol = new CtrlSolicitante();
            int codigoCli = Integer.parseInt(txtCodigo.getText());
            String json;
            //limpaTelaCompleta();
            if (codigoCli > 0) { //Pesquisa direta
                json = ctrlSol.Recuperar(codigoCli);

                if (json.isEmpty()) {
                    if (Mensagem.confirm("Solicitante não encontrado\nDeseja abrir a tela de pesquisa?", this)) {
                        Pesquisa pesq = new Pesquisa(new javax.swing.JFrame(), true, "SOLICITANTE", new String());
                        pesq.setVisible(true);
                        //System.out.println("Identificador retornado: " + pesq.getResultPesq());
                        setJsonTelaSolicitante(ctrlSol.RecuperarSolCRM(pesq.getResultPesq()));
                    }
                } else {
                    setJsonTelaSolicitante(json);
                    controlaAcesso(true);
                }
            } else { //Abre a tela de pesquisa
                setJsonTelaSolicitante(new CtrlSolicitante().RecuperaUltimoRegistro());
            }
        } catch (NumberFormatException ex) {
            txtCodigo.requestFocus();

        } catch (Exception ex) {
            Mensagem.warning(ex.getMessage(), this);
        } finally {
            txtCodigo.selectAll();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCRMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCRMKeyPressed
        if (evt.getKeyCode() == 10) {
            btnSalvarActionPerformed(new java.awt.event.ActionEvent(this, WIDTH, "Salvar"));
        }
    }//GEN-LAST:event_txtCRMKeyPressed

    private void txtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyPressed
        if (evt.getKeyCode() == 10) {
            btnPesquisarActionPerformed(new java.awt.event.ActionEvent(this, WIDTH, "Salvar"));
        }
    }//GEN-LAST:event_txtCodigoKeyPressed

    private void btnProximoSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoSolicitanteActionPerformed
        if(txtCodigo.getText().isEmpty()){
            return;
        }
        if (txtCodigo.getText().equals(new JsonParser().parse(new CtrlSolicitante().RecuperaUltimoRegistro()).getAsJsonObject().get("objCod_objBase").getAsString())) {
            Mensagem.information("Este é o último solicitante !!!", this);
            return;
        }

        String json = new CtrlSolicitante().RecuperaProximoRegistro(Integer.parseInt(txtCodigo.getText()));

        if (json != null) {
            setJsonTelaSolicitante(json);
        }
    }//GEN-LAST:event_btnProximoSolicitanteActionPerformed

    private void btnAnteriorSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorSolicitanteActionPerformed
        //System.out.println("Codigo: " + new JsonParser().parse(new CtrlProduto().RecuperaPrimeiroRegistro()).getAsJsonObject().get("objCod_objBase").getAsString().equals(txtCodigo.getText()));
        if(txtCodigo.getText().isEmpty()){
            return;
        }
        if (txtCodigo.getText().equals(new JsonParser().parse(new CtrlSolicitante().RecuperaPrimeiroRegistro()).getAsJsonObject().get("objCod_objBase").getAsString())) {
            Mensagem.information("Este é o primeiro solicitante !!!", this);
            return;
        }

        String json = new CtrlSolicitante().RecuperaRegistroAnterior(Integer.parseInt(txtCodigo.getText()));

        if (json != null) {
            setJsonTelaSolicitante(json);
        }
    }//GEN-LAST:event_btnAnteriorSolicitanteActionPerformed

    private void btnPrimeiroSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroSolicitanteActionPerformed
        String json = new CtrlSolicitante().RecuperaPrimeiroRegistro();

        if (json != null) {
            setJsonTelaSolicitante(json);
        }
    }//GEN-LAST:event_btnPrimeiroSolicitanteActionPerformed

    private void btnUltimoSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoSolicitanteActionPerformed
        String json = new CtrlSolicitante().RecuperaUltimoRegistro();

        if (json != null) {
            setJsonTelaSolicitante(json);
        }
    }//GEN-LAST:event_btnUltimoSolicitanteActionPerformed

    private void txtCRMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCRMFocusLost
        String texto = txtCRM.getText();
        if (texto == null || texto.isEmpty()) {
            return;
        }

        int size = texto.length();
        for (int i = 0; i < size; i++) {
            if (!Character.isDigit(texto.charAt(i)) && texto.charAt(i) != '.' && texto.charAt(i) != ',') {
                txtCRM.requestFocus();
                txtCRM.selectAll();
                Mensagem.warning("Informe apenas números!!!", this);//System.out.println("Digito");
                return;
            }
        }
    }//GEN-LAST:event_txtCRMFocusLost

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            Solicitante dialog = new Solicitante(new javax.swing.JFrame(), true, -1);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAnteriorSolicitante;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrimeiroSolicitante;
    private javax.swing.JButton btnProximoSolicitante;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimoSolicitante;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCRM;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JTextField txtCRM;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
